//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNETMVCNavigationMenu.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavigationMenu
    {
        public long LinkId { get; set; }
        public int LinkLevel { get; set; }
        public string Linktype { get; set; }
        public long ParentLink { get; set; }
        public int LinkOrder { get; set; }
        public string LinkText { get; set; }
        public bool HasChildren { get; set; }
        public string Class { get; set; }
    }
}
